### ISSUE TITLE
Errors compiling 'src/.../skip_list.h','tests/.../minimum_swaps.cc', 'tests/.../image.cc'  and 'src/.../rmq_sparse_table.h'

### ISSUE THREAD

**Issue by sheldonrobinson** [spirosmaggioros/AlgoPlus#97]
1.  Compile errors caused by missing `#include <numeric>` needed for `iota` in `tests/algorithms/sorting/minimum_swaps.cc`, and `tests/machine_learning/image/image.cc`
1.  Compile error caused by missing `#include <string>` in `src/classes/list/skip_list.h`
1.  Compile error cause by `__builtin_clz` not defined in for `MSVC`

**Comment by spirosmaggioros** [comment]
Hi @sheldonrobinson, thanks for taking the time to look at the project! 
What OS do you have? I'm asking because i believe we are fine on MacOS and Linux(basically Unix based systems). If you have windows it will help us a lot, because the issues appear only there.

**Comment by sheldonrobinson** [comment]
I am using the following compilers

1. MSVC 
    - version 14.42.17.12
    - Windows 11 SDK 10.0.26100.0
    - architecture arm64, x64
1. Android
    - SDK android-35 
    - ndk version 27.2.12479018
    - architecture arm64-v8a

**Comment by spirosmaggioros** [comment]
Yeah, never worked with MSVC. Thank you for testing it with this. Will merge your PR in a couple of hours, tests pass!
